- name: ensure expected variables are defined
  assert:
    that:
    - 'benchmarks is defined'
    - 'local_results_path is defined'
    - 'remote_results_path is defined'

- name: ensure docker-engine is installed
  apt:
    name: docker-engine
    update_cache: yes
    state: latest
  become: true
  when: 'check_docker_package | default(false)'

- name: install statically linked docker
  include_tasks: install-docker-static-binary.yml
  when: 'install_statically_linked_docker | default(false)'

- name: ensure the docker daemon is running
  service:
    name: docker
    state: started
  become: true
  when: 'check_docker_package | default(false)'

- name: stop any running container
  shell: "docker stop `docker ps -q`"
  ignore_errors: true

- name: remove containers to avoid name clashes
  shell: "docker rm `docker ps -qa`"
  ignore_errors: true

- name: ensure results folder exists
  local_action:
    module: file
    path: '{{ local_results_path }}'
    state: directory
    mode: 0755
  run_once: true
