---
- name: get any bench-specific files
  synchronize:
    src: '{{ item }}/'
    dest: '{{ output_folder }}/'
    mode: pull
    use_ssh_args: yes
  with_items: '{{ bench.fetch | default([])}}'
  become: true

- name: delete remote folder after transfer
  file:
    path: '{{ item }}/'
    state: absent
  with_items: '{{ bench.fetch | default([])}}'
  when: remove_benchmark_output | default(true)
  become: true
