---
- name: initialize string for path
  set_fact:
    output_folder: '{{ results_path | default("./results/") }}/benchmark/{{ bench.name }}/machine/{{ inventory_hostname }}'

- name: add key/value pairs for each parameter (if any)
  set_fact:
    output_folder: '{{ output_folder }}/{{ item.key }}/{{ item.value }}'
  with_dict: '{{ params | default({}) }}'
  when: '"hey_ho_lets_go" not in parameter_names'

- name: ensure output folder exists
  local_action:
    module: file
    path: '{{ output_folder }}'
    state: directory
  run_once: true

- name: get any bench-specific files
  synchronize:
    src: '{{ item }}/'
    dest: '{{ output_folder }}/'
    mode: pull
  with_items: '{{ bench.fetch | default([])}}'

- name: delete remote folder after transfer
  file:
    path: '{{ item }}/'
    state: absent
  with_items: '{{ bench.fetch | default([])}}'
  when: '{{ remove_benchmark_output | default(true) }}'
  become: true
