---
- name: get any bench-specific files
  synchronize:
    src: '{{ item }}/'
    dest: '{{ output_folder }}/'
    mode: pull
  with_items: '{{ bench.fetch | default([])}}'

- name: delete remote folder after transfer
  file:
    path: '{{ item }}/'
    state: absent
  with_items: '{{ bench.fetch | default([])}}'
  when: '{{ remove_benchmark_output | default(true) }}'
  become: true
