---
- include: check_preconditions.yml

- name: start monitoring
  include: monitoring-start.yml
  when: '(enable_monitoring | default(false)) == true'

- name: execute each benchmark
  include: run-bench.yml
  with_items: '{{ benchmarks }}'
  loop_control:
    loop_var: benchmark

- name: store facts
  include: store-facts.yml
  when: '{{ store_facts | default(true) }}'

- name: stop monitoring
  include: monitoring-stop.yml
  when: '(enable_monitoring | default(false)) == true'
