---
- name: ensure benchmarks dict exists
  assert:
    that:
    - 'benchmarks is defined'

- name: create results path variable if it wasn't provided
  set_fact:
    results_path: "./results/"
  when: results_path not defined

- name: ensure benchmark output folder exists
  local_action:
    module: file
    path: '{{ results_path }}'
    state: directory

- name: start monitoring
  include: monitoring-start.yml
  when: '(enable_monitoring | default(false)) == true'

- name: execute each benchmark
  include: run-bench.yml
  with_items: '{{ benchmarks }}'
  loop_control:
    loop_var: benchmark

- name: store facts
  include: store-facts.yml
  when: '{{ store_facts | default(true) }}'

- name: stop monitoring
  include: monitoring-stop.yml
  when: '(enable_monitoring | default(false)) == true'
