---
- name: pull image
  command: 'docker pull {{ bench.image }}'

- name: initialize docker_flags variable
  set_fact:
    docker_flags: ''

- name: add environment to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -e {{ item.key }}="{{ item.value }}"'
  with_dict: '{{ bench.env | default({}) }}'
- name: add implicit environment from params variable
  set_fact:
    docker_flags: '{{ docker_flags }} -e {{ item.key }}={{ item.value }}'
  with_dict: '{{ params | default({}) }}'

- name: check if we have host-specific environment
  set_fact:
    env_host_map: '{{ bench.env_host | default({}) }}'
- name: add host-specific environment to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -e {{ item.key }}="{{ item.value }}"'
  with_dict: '{{ env_host_map[inventory_hostname] | default({}) }}'

- name: add devices to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} --device {{ item }}'
  with_items: '{{ bench.devices | default([]) }}'

- name: add network mode to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} --net={{ bench.network_mode }}'
  when: 'bench.network_mode is defined'

- name: add ipc mode to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} --ipc={{ bench.ipc }}'
  when: 'bench.ipc is defined'

- name: add ports to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -p {{ item }}'
  with_items: '{{ bench.ports | default([]) }}'

- name: add volumes to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -v {{ item }}'
  with_items: '{{ bench.volumes | default([]) }}'

- name: set entrypoint
  set_fact:
    docker_flags: '{{ docker_flags }} --entrypoint={{ bench.entrypoint }}'
  when: 'bench.entrypoint is defined'

- name: set limits
  set_fact:
    docker_flags: '{{ docker_flags }} --{{ item.key }}={{ item.value }}'
  with_dict: '{{ bench.limits | default({}) }}'

- name: add capabilities
  set_fact:
    docker_flags: '{{ docker_flags }} --cap-add={{ bench.cap_add | join(', ') }}'
  when: 'bench.cap_add is defined'

- name: remove capabilities
  set_fact:
    docker_flags: '{{ docker_flags }} --cap-drop={{ bench.cap_drop | join(', ') }}'
  when: 'bench.cap_drop is defined'

- name: set privileged mode
  set_fact:
    docker_flags: '{{ docker_flags }} --privileged'
  when: 'bench.privileged | default(False)'

- name: run container
  shell: >
    docker run --rm \
      {{ docker_flags }} \
      {{ bench.image }} \
      {{ bench.command | default("") }}
  async: 10800
  poll: 20
  register: docker_run

- name: record elapsed time in output folder
  local_action: shell echo "{{ docker_run.delta }}" > {{ output_folder }}/runtime
  when: 'measure_runtime | default(true)'
