---
- name: push script
  copy:
    src: '{{ bench.script }}'
    dest: '/tmp/{{ bench.script }}'
    mode: 0755

- name: record time before execution
  local_action: command date +%s
  register: time_before
  run_once: true
  when: 'bench.measure_runtime | default(false)'

- name: time task
  local_action: command date +%s
  register: time_before
  run_once: true
  when: 'bench.measure_runtime | default(false)'

- name: record time after execution
  local_action: command date +%s
  register: time_after
  run_once: true
  when: 'bench.measure_runtime | default(false)'

- name: record elapsed time in output folder
  local_action: shell echo "{{bench.name}},$(({{time_after.stdout}}-{{time_before.stdout}})) >> {{results_folder}}/runtime
  when: 'bench.measure_runtime | default(false)'
