---
- name: upload files
  synchronize:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items: '{{ benchmark.put | default([]) }}'

- name: initialize parameter lists
  set_fact:
    parameter_names: []
    parameter_list: []

- name: unnest parameters when parameters for benchmark were passed
  set_fact:
    parameter_names: '{{ parameter_names + [item.key] }}'
    parameter_list: '{{ parameter_list + [item.value] }}'
  with_dict: '{{ benchmark.parameters | default({"hey_ho_lets_go": 1}) }}'

- name: parametrized execution
  include: run-bench-parametrized.yml
  with_cartesian: '{{ parameter_list }}'
  loop_control:
    loop_var: parameter_values
