---
- name: pull compose image
  command: 'docker pull docker/compose:1.11.1'

- name: write compose file
  copy:
    content: '{{ bench.compose | to_yaml | regex_replace("cpu_quota: ''([0-9]+)''", "cpu_quota: \1") }}'
    dest: "/tmp/docker-compose.yml"

- name: run compose
  shell: >
    docker run --rm --name=compose \
      --volume `which docker`:/usr/bin/docker \
      --volume /var/run/docker.sock:/var/run/docker.sock \
      --volume /tmp/docker-compose.yml:/docker-compose.yml \
      docker/compose:1.11.1 up \
        --force-recreate --abort-on-container-exit
