benchmarks:
- name: redisbench-3.2.11
  compose:
    version: '2'
    services:
      redis:
        image: redis:3.2.11
        network_mode: host
      redisbench:
        image: redis:3.2.11
        entrypoint: /bin/bash
        command: -c "
          sleep 10 &&
          redis-benchmark -d 8 -r 1000000 -n 20000000 -t get,set,lpush,lpop -P 4 --csv > /results/out.csv"
        volumes:
        - '/tmp/results:/results'
  fetch:
  - '/tmp/results'
