---
- name: check that required variables are defined
  assert:
    that: 'bench is defined and
           all_results is defined and
           docker_flags_machine[ansible_hostname] is defined'

- name: run bench
  shell: >
    docker run {{ docker_flags_all }} \
               {{ docker_flags_machine[ansible_hostname] }} \
               {{ bench.docker_flags }} \
               {{ bench.image_name }} \
               {{ bench.image_args }}
  register: docker_output

- name: add results to global variable
  set_fact:
    all_results: '{{
      all_results |
        union(
          [{
            "id": bench.id,
            "docker_flags": (docker_flags_all + " " +
                             docker_flags_machine[ansible_hostname] + " " +
                             bench.docker_flags),
            "image_name": bench.image_name,
            "image_args": bench.image_args,
            "tests": (docker_output.stdout | from_json)
          }]
        )
    }}'
