---
- name: ensure benchmarks dict exists
  assert:
    that:
    - 'benchmarks is defined'

- name: run benchmarks
  include: run-bench.yml
  with_items: '{{ benchmarks }}'
  loop_control:
    loop_var: bench

- name: create facts folder if it don't exist
  local_action:
    module: file
    path: ./facts
    state: directory
    mode: 0755
  run_once: true

- name: store facts about remotes
  local_action:
    module: copy
    content: '{{ hostvars[item] | to_nice_json }}'
    dest: ./facts/{{ item }}.json
  run_once: true
  with_items: '{{ groups.all }}'
  when: 'item != "localhost"'
