---
- name: ensure benchmarks dict exists
  assert:
    that:
    - 'benchmarks is defined'

- name: unnest parameters
  set_fact:
    parameter_names: '{{ (parameter_names | default([])) + [item.key] }}'
    parameter_list: '{{ (parameter_list | default([])) +  [item.value] }}'
  with_dict: '{{ parameters | default({}) }}'

- name: parametrized execution
  include: run-bench-parametrized.yml
  with_cartesian: '{{ parameter_list }}'
  loop_control:
    loop_var: parameter_values
  when: 'parameters is defined'

- name: non-parametrized execution
  include: run-bench.yml
  with_items: '{{ benchmarks }}'
  loop_control:
    loop_var: bench
  when: 'parameters is not defined'

- name: create facts folder if it doesn't exist
  local_action:
    module: file
    path: ./facts
    state: directory
    mode: 0755
  run_once: true

- name: store facts about remotes
  local_action:
    module: copy
    content: '{{ hostvars[item] | to_nice_json }}'
    dest: ./facts/{{ item }}.json
  run_once: true
  with_items: '{{ groups.all }}'
  when: 'item != "localhost"'
