---
- name: ensure benchmarks dict exists
  assert:
    that:
    - 'benchmarks is defined'

- name: execute each benchmark
  include: run-bench.yml
  with_items: '{{ benchmarks }}'
  loop_control:
    loop_var: benchmark

- name: store facts
  include: store-facts.yml
  when: '{{ store_facts | default(true) }}'
