---
- name: ensure benchmarks dict exists
  assert:
    that:
    - 'benchmarks is defined'
    - 'docker_flags_global is defined'

- name: ensure that every item in benchmarks dict has all expected variables
  assert:
    that: 'item.id is defined and item.image_name is defined and 
           item.image_args is defined and item.docker_flags is defined'
  with_items: '{{ benchmarks }}'

- name: pull images
  shell: docker pull {{ item.image_name }}
  with_items: '{{ benchmarks }}'

- name: reset results variable that gets populated in bench.yml
  set_fact:
    all_results: []

- name: run benchmarks
  include: bench.yml bench={{item}} docker_flags_all={{ docker_flags_global }}
  with_items: '{{ benchmarks }}'

- name: define results variable
  local_action:
    module: set_fact
    results: {}
  run_once: true

- name: populate results variable
  local_action:
    module: set_fact
    results: '{{ results |
      combine(
        { item: hostvars[item]["all_results"] },
        recursive=True)  }}'
  with_items: '{{ play_hosts }}'
  when: 'item != "localhost"'
  run_once: true

- name: store results
  local_action: copy content={{ results }} dest=./results.json
  run_once: true
