---
- name: check that required variables are defined
  assert:
    that: 'bench is defined'

# upload files
- name: upload files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items: '{{ bench.put }}'

- name: run containerized benchmark
  include: run-container.yml
  when: 'bench.image is defined'
