---
- name: check that required variables are defined
  assert:
    that: 'bench is defined and all_results is defined'

- name: pull container
  command: 'docker pull {{ bench.image }}'

# upload files
- name: upload files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items: '{{ bench.put }}'

- name: initialize docker_flags variable
  set_fact:
    docker_flags: '--name={{ bench.name }}'

# remove
- name: stop container
  command: 'docker stop {{ bench.name }}'
  ignore_errors: true
- name: remove container
  command: 'docker rm {{ bench.name }}'
  ignore_errors: true

# environment
- name: add environment to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags}} -e {{ item.key }}="{{ item.value }}"'
  with_dict: '{{ bench.env }}'
  when: 'bench.env is defined'

# host-specific environment
- name: initialize env_host
  set_fact:
    env_host: {}

- name: check if there is a host-specific environment
  set_fact:
    env_host: '{{ bench.env_host[ansible_hostname] }}'
  when:
  - 'bench.env_host is defined'
  - 'ansible_hostname in bench.env_host'

- name: add host-specific environment to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -e {{ item.key }}="{{ item.value }}"'
  with_dict: '{{ env_host }}'

# network_mode
- name: add network mode to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} --net={{ bench.network_mode }}'
  when: 'bench.network_mode is defined'

# volumes
- name: add volumes args
  set_fact:
    docker_flags: '{{ docker_flags }} -v {{ item }}'
  with_items: '{{ bench.volumes }}'

# container arguments
- name: set args value
  set_fact:
    container_args: '{{ ( bench.args | default("") }}'

# run
- name: initialize bench output variable
  set_fact:
    all_repetitions: []

- name: run container
  shell: docker run --rm {{ docker_flags }} {{ bench.image }} {{ container_args }}
  register: docker_output
  with_sequence: count='{{bench.repetitions}}'

# process results
- name: add result to all repetitions variable
  set_fact:
    all_repetitions: '{{ (all_repetitions + (item.stdout | from_json)) }}'
  with_items: '{{ docker_output.results }}'

- name: add results to global variable
  set_fact:
    all_results: '{{
      all_results | union(
        [{
          "id": bench.id,
          "repetitions": repetitions,
          "tests": all_repetitions
        }]
      )
    }}'
