---
- name: pull image
  command: 'docker pull {{ bench.image }}'

- name: initialize docker_flags variable
  set_fact:
    docker_flags: ''

- name: stop container
  shell: 'docker stop $(docker ps -aq --filter ancestor={{ bench.image }})'
  ignore_errors: true
- name: remove container
  shell: 'docker rm $(docker ps -aq --filter ancestor={{ bench.image }})'
  ignore_errors: true

- name: add environment to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -e {{ item.key }}="{{ item.value }}"'
  with_dict: '{{ bench.env | default({}) }}'
- name: add implicit environment from params variable
  set_fact:
    docker_flags: '{{ docker_flags }} -e {{ item.key }}={{ item.value }}'
  with_dict: '{{ params | default({}) }}'

- name: check if we have host-specific environment
  set_fact:
    env_host_map: '{{ bench.env_host | default({}) }}'
- name: add host-specific environment to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -e {{ item.key }}="{{ item.value }}"'
  with_dict: '{{ env_host_map[ansible_hostname] | default({}) }}'

- name: add devices to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} --device {{ item }}'
  with_items: '{{ bench.devices | default([]) }}'

- name: add network mode to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} --net={{ bench.network_mode }}'
  when: 'bench.network_mode is defined'

- name: add ports to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -p {{ item }}'
  with_items: '{{ bench.ports | default([]) }}'

- name: add volumes to docker_flags
  set_fact:
    docker_flags: '{{ docker_flags }} -v {{ item }}'
  with_items: '{{ bench.volumes | default([]) }}'

- name: set entrypoint to /bin/bash when 'args' is given
  set_fact:
    docker_flags: '{{ docker_flags }} --entrypoint=/bin/bash'
    container_args: " -c '{{ bench.args }}'"
  when: 'bench.args is defined'

- name: run container
  shell: >
    docker run --rm --name={{ bench.name }}-{{ ansible_hostname }} \
      {{ docker_flags }} \
      {{ bench.image }} \
      {{ container_args | default("") }}
