---
- name: create parameter dictionary
  set_fact:
    params: '{{ params | default({}) | combine({item.0: item.1})}}'
  with_together:
  - '{{ parameter_names }}'
  - '{{ parameter_values }}'

- name: merge default variables to the bench setup
  set_fact:
    bench: '{{ (defaults | default({})) | combine(benchmark) }}'

- name: run containerized benchmark
  include: run-container.yml
  when: 'bench.image is defined'

- name: run script benchmark
  include: run-script.yml
  when: 'bench.script is defined'

- name: download results
  include: download-output.yml
  when: 'bench.fetch is defined'
